function configureSystem(this)
  configureSystem@Test.Approximation(this);

  floorplan = Utils.resolvePath(sprintf('%03d.flp', this.processorCount));
  hotspotConfig = Utils.resolvePath('hotspot.config');
  hotspotLine = sprintf('sampling_intvl %e', this.samplingInterval);

  this.power = DynamicPower( ...
    'platform', this.platform, ...
    'application', this.application, ...
    'samplingInterval', this.samplingInterval);

  this.temperature = Temperature.Analytical.Transient( ...
    'floorplan', floorplan, ...
    'hotspotConfig', hotspotConfig, ...
    'hotspotLine', hotspotLine, ...
    'samplingInterval', this.samplingInterval, ...
    'processorCount', this.processorCount);
end
