function configureMethod(this)
  switch this.method
  case 'PC'
    this.methodOptions = Options( ...
      'basis', 'Hermite', ...
      'quadratureOptions', Options( ...
        'method', 'sparse', ...
        'dimension', this.inputCount, ...
        'order', 3), ...
      'inputCount', this.inputCount, ...
      'outputCount', this.outputCount, ...
      'order', 2, ...
      this.methodOptions);

    this.methodSerialization{end + 1} = ...
      this.methodOptions.order;
    this.methodSerialization{end + 1} = ...
      this.methodOptions.quadratureOptions.order;
  case 'SC'
    this.methodOptions = Options( ...
      'support', 'Local', ...
      'inputCount', this.inputCount, ...
      'outputCount', this.outputCount, ...
      'absoluteTolerance', 1e-4, ...
      'relativeTolerance', 1e-2, ...
      'maximalLevel', 10, ...
      'verbose', true, ...
      this.methodOptions);
  otherwise
    assert(false);
  end
end
