function display(this)
  options = Options( ...
    'Inputs', this.inputCount, ...
    'Outputs', this.outputCount, ...
    'Agents', this.agentCount, ...
    'Level', this.level, ...
    'Nodes', this.nodeCount, ...
    'Last nodes', this.levelNodeCount(end));
  display(options, 'Adaptive sparse grid collocation');
end
