function assessApproximation(this)
  fprintf('Expectation:\n');
  fprintf('  Normalized L2:   %.4e\n', ...
    Error.computeNL2(this.mcExpectation, this.apExpectation));
  fprintf('  Normalized RMSE: %.4e\n', ...
    Error.computeNRMSE(this.mcExpectation, this.apExpectation));

  fprintf('Variance:\n');
  fprintf('  Normalized L2:   %.4e\n', ...
    Error.computeNL2(this.mcVariance, this.apVariance));
  fprintf('  Normalized RMSE: %.4e\n', ...
    Error.computeNRMSE(this.mcVariance, this.apVariance));

  fprintf('Random sampling:\n');
  fprintf('  Normalized L2:   %.4e\n', ...
    Error.computeNL2(this.mcData, this.apData));
  fprintf('  Normalized RMSE: %.4e\n', ...
    Error.computeNRMSE(this.mcData, this.apData));
end
